# These are supported funding model platforms

buy_me_a_coffee: tonycannistra # Replace with a single Buy Me a Coffee username
custom: https://account.venmo.com/u/tcannistra # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
