name: Send Avalanche Forecast Emails
on: 
  schedule: 
    - cron: '2,32 * * * *'
  workflow_dispatch:
jobs: 
  SendEmails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install poetry==1.0.0
      - run: poetry export -f requirements.txt --output requirements.txt --without-hashes
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install --no-cache-dir --upgrade -r requirements.txt