name: Send Avalanche Forecast Emails
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  SendEmails:
    runs-on: ubuntu-latest
    environment: sendemail
    steps:
      - uses: actions/checkout@v3
      - run: pip install poetry==1.0.0
      - run: poetry export -f requirements.txt --output requirements.txt --without-hashes
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        run: python3 ./send-avymail.py
